version: "3.9"
name: kitchen-service
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "kitchen-service"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5437:5432"
