server:
  port: 8081
spring:
  application:
    name: kitchen-service
  datasource:
    url: jdbc:postgresql://localhost:5437/kitchen-service
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: public
#  kafka:
#    bootstrap-servers:
#      - localhost:29092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      number-topic: ordersTopic
#      created-topic: createdTopic
#      properties:
#        acks: 1
feign:
  value: "waiter-service-api"
  url: localhost:8082
management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
  endpoint:
    health:
      show-details: ALWAYS