server:
  port: 8081
spring:
  application:
    name: kitchen-service
  datasource:
    url: jdbc:postgresql://localhost:5437/kitchen-service
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: public
management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
  endpoint:
    health:
      show-details: ALWAYS