server:
  port: 8081
spring:
  application:
    name: kitchen-service
  datasource:
    url: jdbc:postgresql://localhost:5437/kitchen-service
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: public
  kafka:
    bootstrap-servers:
      - localhost:29092
    producer:
      created-topic: ordersTopic
    consumer:
      group-id: order-consumer
      concurrency: 2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            value:
              default:
                type: ru.liga.kitchenservice.model.dto.KitchenOrderDto

feign:
  value: "waiter-service-api"
  url: localhost:8082
management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
  endpoint:
    health:
      show-details: ALWAYS