server:
  port: 8082
spring:
  application:
    name: waiter-service
  datasource:
    url: jdbc:postgresql://localhost:5438/waiter-service
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: public
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml



management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
  endpoint:
    health:
      show-details: ALWAYS
