server:
  port: 8082
spring:
  application:
    name: waiter-service
  datasource:
    url: jdbc:postgresql://localhost:5438/waiter-service
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: public
  kafka:
    bootstrap-servers:
      - localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      created-topic: ordersTopic
      properties:
        acks: 1
feign:
  value: "kitchen-service-api"
  url: localhost:8081
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
  endpoint:
    health:
      show-details: ALWAYS
