version: "3.9"
name: waiter-service
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "waiter-service"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5438:5432"
